### ISSUE TITLE
Deprecated Pillow methods used 

### ISSUE THREAD

**Issue by rolisz** [adrienverge/PhotoCollage#18]
If you use Pillow 3.0.0, which came out last month, you get the following stack trace:

Process RenderingProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/site-packages/photocollage/render.py", line 145, in run
    self.wr_conn.send(self.fn(*self.fn_args, **self.fn_kwargs))
  File "/usr/lib/python3.5/site-packages/photocollage/render.py", line 288, in resize_photo
    return img.size[0], img.size[1], img.tostring()
  File "/usr/lib/python3.5/site-packages/PIL/Image.py", line 686, in tostring
    "Please call tobytes() instead.")

Images don't render because of this. It works if you install 2.9.0

**Comment by adrienverge** [comment]
Thanks @rolisz!
