### ISSUE TITLE
No module named 'cairo'

### ISSUE THREAD

**Issue by chichivica** [adrienverge/PhotoCollage#48]
Hi there! Many thanks for great project.

Either pip3 and manual installation produce the same:

```
Traceback (most recent call last):
  File "/home/chichivica/anaconda3/bin/photocollage", line 21, in <module>
    from photocollage import gtkgui
  File "/home/chichivica/Programs/PhotoCollage/photocollage/gtkgui.py", line 26, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
```
I installed cairo, cairocffi, 
but pycairo could not:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pycairo -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```
May be I miss understand smth?

**Comment by chichivica** [comment]
Oh sorry for that, the problem was in ANACONDA. 
Don't use that shit. I'm facing collisions with anaconda all the time when I'm installing smth.

**Comment by ojob** [comment]
Or maybe you missed that [anaconda provides a very nice way to install python packages](https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-packages) ? You may not want to use `pip` in that case.

**Comment by Lykos153** [comment]
Same problem here. The instructions for Arch Linux don't seem to be sufficient as it's necessary to install `python-cairo` as well.

**Comment by harriott** [comment]
In an Arch Linux, Python 3.8.1 & python-cairo 1.18.2-3, I'm still getting:
`Traceback (most recent call last):
  File "/home/jo/.virtualenvs/photocollage/bin/photocollage", line 21, in <module>
    from photocollage import gtkgui
  File "/home/jo/.virtualenvs/photocollage/lib/python3.8/site-packages/photocollage/gtkgui.py", line 26, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
`

**Comment by mquevill** [comment]
This should probably be addressed with a `install_requires` in the `setup.py`.

To use this with Conda, I had to install a few extra packages with this command:
`conda install -c conda-forge gtk3 pillow pycairo pygobject`
