### ISSUE TITLE
cannot import name GdkPixbuf, introspection typelib not found

### ISSUE THREAD

**Issue by Drjacky** [adrienverge/PhotoCollage#82]
```python
➜  ~ photocollage
Traceback (most recent call last):
  File "/usr/local/bin/photocollage", line 21, in <module>
    from photocollage import gtkgui
  File "/usr/local/lib/python3.9/site-packages/photocollage/gtkgui.py", line 29, in <module>
    from photocollage import APP_NAME, artwork, collage, render
  File "/usr/local/lib/python3.9/site-packages/photocollage/artwork.py", line 21, in <module>
    from gi.repository import GdkPixbuf
  File "/usr/local/lib/python3.9/site-packages/gi/importer.py", line 131, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GdkPixbuf, introspection typelib not found
```

**Comment by rljacobson** [comment]
I don't know if this is the same issue as yours, but I had to modify the import in `artwork.py` to be:

```python
import gi

gi.require_version('GdkPixbuf', '2.0')
from gi.repository import GdkPixbuf
```

I still haven't gotten it to run correctly, but at least I got rid of the error complaining about `GdkPixbuf`.
